packages:
  - apps/dwi-host
  - apps/dwi-webview
  - packages/dwi-core
  - packages/domain/prompt-optimizer
  - packages/domain/workspace
allowBuilds:
  '@swc/core': true
  '@vscode/vsce-sign': true
  keytar: true
