import React, { useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import { DWI_FUTURE_INTEGRATIONS, DWI_MODULES, compileDwiCandidate, createFeedback, evaluationMarkdown, type DwiBrief } from "@platform/dwi-core";
import "./styles.css";
import "./compose.css";

type Stage = "consent" | "brief" | "compose" | "evaluate";
type DwiWorkspaceSnapshot = { status: "partial" | "complete"; stage: Stage; brief?: DwiBrief; selectedModuleIds?: string[]; candidate?: ReturnType<typeof compileDwiCandidate>; evaluationMarkdown?: string };
const demoBrief: DwiBrief = { version: "dwi.brief.v1", projectName: "Platform workspace", archetype: "TypeScript monorepo", stack: ["TypeScript", "React", "Node.js"], packageManager: "pnpm", scripts: ["build", "lint", "typecheck", "test"], modules: ["apps", "packages", "tools"], facts: [
  { id: "manifest", label: "Workspace", value: "pnpm + Turborepo", confidence: "high", evidence: "pnpm-workspace.yaml · package.json" },
  { id: "frontend", label: "UI", value: "React + Vite", confidence: "high", evidence: "apps/* manifests" },
  { id: "runtime", label: "Runtime", value: "Node.js", confidence: "high", evidence: "engines.node" },
], unknowns: ["Deployment target", "Feature-specific acceptance criteria"], confirmed: false, corrections: "" };
declare const acquireVsCodeApi: undefined | (() => { postMessage(message: unknown): void });
const vscode = typeof acquireVsCodeApi === "function" ? acquireVsCodeApi() : undefined;

function App() {
  const [stage, setStage] = useState<Stage>("consent"); const [brief, setBrief] = useState(demoBrief);
  const [selected, setSelected] = useState(() => DWI_MODULES.filter((m) => m.defaultSelected).map((m) => m.id));
  const [candidate, setCandidate] = useState<ReturnType<typeof compileDwiCandidate>>(); const [note, setNote] = useState(""); const [draft, setDraft] = useState(""); const [isApproving, setIsApproving] = useState(false); const [consentError, setConsentError] = useState(""); const [expandedEvidenceId, setExpandedEvidenceId] = useState<string>(); const [expandedModuleId, setExpandedModuleId] = useState<string>(); const [savedState, setSavedState] = useState<{ kind: "partial" | "recovery" | "generic"; snapshot?: DwiWorkspaceSnapshot }>(); const [roots, setRoots] = useState<Array<{ uri: string; label: string; fingerprint: string }>>([]); const [settingsOpen, setSettingsOpen] = useState(false); const [provider, setProvider] = useState<{ mode: "none" | "gemini" | "openai-compatible"; model?: string; baseUrl?: string; configured: boolean }>({ mode: "none", configured: false }); const [settingsError, setSettingsError] = useState("");
  const step = ["consent", "brief", "compose", "evaluate"].indexOf(stage) + 1;
  const selectedModules = useMemo(() => DWI_MODULES.filter((m) => selected.includes(m.id)), [selected]);
  useEffect(() => { const listener = (event: MessageEvent<{ type?: string; brief?: DwiBrief; candidate?: ReturnType<typeof compileDwiCandidate>; message?: string; snapshot?: DwiWorkspaceSnapshot }>) => { if (event.data.type === "dwi.consent.loading") { setIsApproving(true); setConsentError(""); } if (event.data.type === "dwi.brief.ready" && event.data.brief) { setBrief(event.data.brief); setIsApproving(false); setStage("brief"); } if (event.data.type === "dwi.snapshot.complete" && event.data.snapshot?.brief && event.data.snapshot.candidate) { setBrief(event.data.snapshot.brief); setSelected(event.data.snapshot.selectedModuleIds ?? []); setCandidate(event.data.snapshot.candidate); setDraft(event.data.snapshot.evaluationMarkdown ?? ""); setStage("evaluate"); } if (event.data.type === "dwi.snapshot.partial") setSavedState({ kind: "partial", snapshot: event.data.snapshot }); if (event.data.type === "dwi.snapshot.recovery") setSavedState({ kind: "recovery" }); if (event.data.type === "dwi.session.generic") setSavedState({ kind: "generic" }); if (event.data.type === "dwi.workspace.changed") { setCandidate(undefined); setDraft(""); setSelected(DWI_MODULES.filter((m) => m.defaultSelected).map((m) => m.id)); setStage("consent"); vscode?.postMessage({ type: "dwi.session.open" }); } if (event.data.type === "dwi.error") { setIsApproving(false); setConsentError(event.data.message ?? "DWI could not create a local project brief."); } if (event.data.type === "dwi.candidate.ready" && event.data.candidate) { setCandidate(event.data.candidate); setStage("evaluate"); } }; window.addEventListener("message", listener); vscode?.postMessage({ type: "dwi.session.open" }); return () => window.removeEventListener("message", listener); }, []);
  useEffect(() => { if (vscode && stage !== "consent" && !savedState) vscode.postMessage({ type: "dwi.snapshot.partial", snapshot: { stage, brief, selectedModuleIds: selected, candidate } }); }, [stage, brief, selected, candidate, savedState]);
  useEffect(() => { const listener = (event: MessageEvent<{ type?: string; settings?: typeof provider; message?: string }>) => { if ((event.data.type === "dwi.provider.state" || event.data.type === "dwi.provider.saved") && event.data.settings) { setProvider(event.data.settings); setSettingsError(""); } if (event.data.type === "dwi.provider.error") setSettingsError(event.data.message ?? "Settings could not be saved."); }; window.addEventListener("message", listener); return () => window.removeEventListener("message", listener); }, []);
  useEffect(() => { const listener = (event: MessageEvent<{ type?: string; roots?: Array<{ uri: string; label: string; fingerprint: string }> }>) => { if (event.data.type === "dwi.workspace.choose-root") setRoots(event.data.roots ?? []); }; window.addEventListener("message", listener); return () => window.removeEventListener("message", listener); }, []);
  useEffect(() => { if (settingsOpen) vscode?.postMessage({ type: "dwi.provider.get" }); }, [settingsOpen]);
  function approve() { setConsentError(""); setIsApproving(true); if (vscode) vscode.postMessage({ type: "dwi.consent.approve" }); else { setIsApproving(false); setStage("brief"); } }
  function compile() { setCandidate(compileDwiCandidate({ ...brief, confirmed: true }, selected)); setStage("evaluate"); }
  function feedback(rating: "helpful" | "mixed" | "not-helpful") { if (!candidate) return; const input = { rating, tags: ["feature-delivery"], note, selectedModuleIds: candidate.selectedModuleIds, estimate: candidate.estimate, elapsedMs: 0 }; const event = createFeedback(input); const markdown = evaluationMarkdown(event, brief); vscode?.postMessage({ type: "dwi.feedback.record", feedback: input }); vscode?.postMessage({ type: "dwi.journey.complete", feedback: input, snapshot: { stage: "evaluate", brief, selectedModuleIds: candidate.selectedModuleIds, candidate, evaluationMarkdown: markdown } }); setDraft(markdown); }
  return <main className="shell">
    <header><div className="brand"><span className="mark">D</span><div><strong>Developer Work Intelligence</strong><small>{savedState?.kind === "generic" ? "Generic default mode" : "Local project workspace"}</small></div></div><div className="header-actions"><span className="privacy">● LOCAL ONLY</span><button className="settings-gear" type="button" aria-label="DWI settings" title="DWI settings" onClick={() => setSettingsOpen(true)}>⚙</button></div></header>
    <nav aria-label="Progress">{["Consent", "Brief", "Compose", "Review"].map((label, i) => <span className={i + 1 <= step ? "active" : ""} key={label}><b>{i + 1}</b>{label}</span>)}</nav>
    <section className={`content${savedState ? " recovery-active" : ""}${savedState?.kind === "generic" ? " generic-active" : ""}${settingsOpen ? " settings-active" : ""}${roots.length ? " settings-active" : ""}`}>
      {roots.length > 0 && <article className="card settings-card"><div className="eyebrow">MULTI-ROOT WORKSPACE</div><h2>Choose a project root</h2><p className="lede">DWI keeps context and `.dwi` artifacts isolated to one selected root.</p>{roots.map((root) => <button className="secondary root-choice" key={root.uri} onClick={() => { vscode?.postMessage({ type: "dwi.workspace.select-root", uri: root.uri }); setRoots([]); }}>{root.label}</button>)}</article>}
      {settingsOpen && <article className="card settings-card"><div className="section-head"><div><div className="eyebrow">LOCAL LLM SETTINGS</div><h2>Connect an LLM</h2></div><button className="secondary" onClick={() => setSettingsOpen(false)}>Back</button></div><p className="lede">Optional configuration only. Saving never tests a connection.</p><label className="field">Provider <select value={provider.mode} onChange={(e) => setProvider({ ...provider, mode: e.target.value as typeof provider.mode, configured: false })}><option value="none">No provider</option><option value="gemini">Gemini</option><option value="openai-compatible">OpenAI-compatible</option></select></label>{provider.mode !== "none" && <label className="field">Model <input defaultValue={provider.model} name="model" /></label>}{provider.mode === "openai-compatible" && <label className="field">Base URL <input defaultValue={provider.baseUrl} name="baseUrl" placeholder="https://…" /></label>}{provider.mode !== "none" && <label className="field">API key <input type="password" name="apiKey" autoComplete="off" placeholder="Stored only in VS Code SecretStorage" /></label>}<button className="primary" onClick={(event) => { const form = event.currentTarget.closest("article") as HTMLElement; const model = (form.querySelector('[name="model"]') as HTMLInputElement | null)?.value ?? ""; const baseUrl = (form.querySelector('[name="baseUrl"]') as HTMLInputElement | null)?.value; const key = (form.querySelector('[name="apiKey"]') as HTMLInputElement | null)?.value; if (provider.mode === "none") { setProvider({ mode: "none", configured: false }); setSettingsError(""); return; } vscode?.postMessage({ type: "dwi.provider.save", settings: { mode: provider.mode, model, baseUrl, key } }); if (form.querySelector('[name="apiKey"]')) (form.querySelector('[name="apiKey"]') as HTMLInputElement).value = ""; }}>Save local settings</button>{settingsError && <p className="error" role="alert">{settingsError}</p>}<p className="lede">Status: {provider.configured ? `${provider.mode} configured` : "No provider configured — deterministic local mode remains available."}</p></article>}
      {stage === "consent" && savedState && <article className="hero card consent-card resume-card"><div className="consent-intro"><div className="eyebrow">WORKSPACE DWI STATE</div><h1>{savedState.kind === "partial" ? "Resume partial setup" : "Safely start a new setup"}</h1><p>{savedState.kind === "partial" ? "A managed local DWI partial snapshot is available. Continue preserves its project context; Start over replaces only managed DWI artifacts." : "Existing DWI files are incomplete, unsupported, or include unrecognized content. Fresh setup preserves unrecognized files recoverably."}</p></div><div className="consent-actions"><button className="primary" onClick={() => { const snapshot = savedState.snapshot; if (snapshot?.brief) setBrief(snapshot.brief); if (snapshot?.selectedModuleIds) setSelected(snapshot.selectedModuleIds); setStage(snapshot?.stage ?? "brief"); setSavedState(undefined); }}>Continue partial setup <span>→</span></button><button className="quiet" onClick={() => { vscode?.postMessage({ type: "dwi.snapshot.reset" }); setSavedState(undefined); }}>Start over</button></div></article>}
      {stage === "consent" && <article className="hero card consent-card"><div className="consent-intro"><div className="eyebrow">PROJECT-SCOPED CONSENT</div><h1>Understand this workspace before you start</h1><p>DWI creates a local, evidence-backed project brief and a reviewable feature-delivery prompt. Nothing leaves VS Code.</p></div><div className="consent-body"><div className="scope-grid">{[["Manifests", "Stack and package manager"], ["Docs", "Architecture clues"], ["Scripts", "Available verification"], ["Symbols", "Workspace structure"], ["Retrieval", "Bounded exact matches"]].map(([a,b]) => <div key={a}><i>✓</i><span><strong>{a}</strong><small>{b}</small></span></div>)}</div><section className="exclusions" aria-label="Always excluded"><div><span className="eyebrow">ALWAYS EXCLUDED</span><strong>Private and generated material stays out</strong></div><ul><li>Secrets &amp; environment files</li><li>Dependencies, caches &amp; output</li><li>Private paths &amp; unrestricted source</li></ul></section><details><summary>See exact consent boundaries</summary><p>No background indexing. DWI reads only the approved categories above, after consent, and returns bounded local evidence to the webview.</p></details></div>{consentError && <p className="error" role="alert"><strong>Open a workspace first.</strong> {consentError}</p>}<div className="consent-actions"><button className="primary" onClick={approve} disabled={isApproving}>{isApproving ? "Creating local brief…" : <>Approve & create brief <span>→</span></>}</button><button className="quiet" onClick={() => alert("Analysis declined. No workspace data was read.")}>Decline</button></div></article>}
      {stage === "brief" && <article className="card"><div className="section-head"><div><div className="eyebrow">PROJECT BRIEF · DRAFT</div><h2>{brief.projectName}</h2></div><span className="confidence">HIGH CONFIDENCE</span></div><p className="lede">A deterministic summary from approved local evidence. Confirm it, or add a correction that remains explicit and removable.</p><div className="facts">{brief.facts.map((fact) => <React.Fragment key={fact.id}><div><small>{fact.label}</small><strong>{fact.value}</strong><button type="button" aria-expanded={expandedEvidenceId === fact.id} aria-controls={`evidence-${fact.id}`} onClick={() => setExpandedEvidenceId(expandedEvidenceId === fact.id ? undefined : fact.id)}>{expandedEvidenceId === fact.id ? "Hide evidence" : "Show evidence"}</button></div>{expandedEvidenceId === fact.id && <section className="evidence-card" id={`evidence-${fact.id}`} role={fact.evidence ? "status" : "alert"}><strong>{fact.evidence ? "Local evidence" : "Evidence unavailable"}</strong><p>{fact.evidence || "The approved source for this fact is unavailable. Recreate the brief after opening the workspace."}</p></section>}</React.Fragment>)}</div><label className="field">Corrections or context <textarea value={brief.corrections} onChange={(e) => setBrief({ ...brief, corrections: e.target.value })} maxLength={500} placeholder="Optional — e.g. the API is the primary delivery surface" /></label><details><summary>Unknowns ({brief.unknowns.length})</summary><ul>{brief.unknowns.map((u) => <li key={u}>{u}</li>)}</ul></details><div className="actions"><button className="secondary" onClick={() => setStage("consent")}>Back</button><button className="primary" onClick={() => { setBrief({ ...brief, confirmed: true }); setStage("compose"); }}>Confirm brief <span>→</span></button></div></article>}
      {stage === "compose" && <article className="card compose"><div className="section-head"><div><div className="eyebrow">FEATURE DELIVERY · DEFAULT INTENT</div><h2>Choose the intelligence to include</h2></div><div className="selection-summary"><span>Selected</span><strong className="count" aria-label={`${selected.length} modules selected`}>{selected.length}</strong></div></div><p className="lede">Select the work modules to include. Use the details control for local context.</p><div className="module-list">{DWI_MODULES.map((m) => <div className={`${selected.includes(m.id) ? "module selected" : "module"}${expandedModuleId === m.id ? " details-open" : ""}`} key={m.id} onKeyDown={(event) => { if (event.key === "Escape" && expandedModuleId === m.id) { event.stopPropagation(); setExpandedModuleId(undefined); } }}><label className="module-choice"><input type="checkbox" checked={selected.includes(m.id)} onChange={() => setSelected(selected.includes(m.id) ? selected.filter((id) => id !== m.id) : [...selected, m.id])}/><strong>{m.title}</strong></label><button type="button" className="module-detail-trigger" aria-label={`${expandedModuleId === m.id ? "Hide" : "Show"} ${m.title} details`} aria-expanded={expandedModuleId === m.id} aria-controls={`module-details-${m.id}`} onClick={() => setExpandedModuleId(expandedModuleId === m.id ? undefined : m.id)}>i</button><section className="module-details" id={`module-details-${m.id}`} aria-hidden={expandedModuleId !== m.id}><strong>{m.title}</strong><p>{m.description}</p><p><b>Why:</b> {m.why}</p><small>{m.estimatedTokens} estimated tokens</small><span className="module-details-hint">Press Escape or use the details control to close.</span></section></div>)}</div><details><summary>Future connections</summary>{DWI_FUTURE_INTEGRATIONS.map((x) => <p key={x.owner}><b>{x.owner.toUpperCase()} · disabled</b> — {x.explanation}</p>)}</details><div className="actions"><button className="secondary" onClick={() => setStage("brief")}>Revise brief</button><button className="primary" disabled={!selectedModules.length} onClick={compile}>Compile candidate <span>→</span></button></div></article>}
      {stage === "evaluate" && candidate && <article className="card review"><div className="section-head"><div><div className="eyebrow">PROVIDER-FREE CANDIDATE</div><h2>Ready for human review</h2></div><span className="confidence">LOCAL</span></div><div className="economics"><div><small>Repeated briefing</small><strong>{candidate.estimate.baselineTokens}</strong></div><div><small>Optimized candidate</small><strong>{candidate.estimate.optimizedTokens}</strong></div><div className="saved"><small>Est. avoided duplication</small><strong>{candidate.estimate.estimatedAvoidedDuplication}</strong></div></div><small className="disclaimer">{candidate.estimate.method}</small><details open><summary>Compiled candidate</summary><pre>{candidate.text}</pre></details><label className="field">Private session note <textarea value={note} onChange={(e) => setNote(e.target.value)} maxLength={500} placeholder="Optional, stored locally only" /></label><div className="feedback"><span>Was this useful?</span>{(["helpful", "mixed", "not-helpful"] as const).map((r) => <button key={r} onClick={() => feedback(r)}>{r}</button>)}</div>{draft && <div className="draft"><strong>Evaluation draft generated</strong><p>Human decision, status, and evidence remain intentionally blank.</p><button onClick={() => navigator.clipboard?.writeText(draft)}>Copy Markdown</button><button onClick={() => candidate && vscode?.postMessage({ type: "dwi.evaluation.export", brief, feedback: { rating: "helpful", tags: ["feature-delivery"], note, selectedModuleIds: candidate.selectedModuleIds, estimate: candidate.estimate, elapsedMs: 0 } })}>Export…</button><button onClick={() => vscode?.postMessage({ type: "dwi.feedback.delete" })}>Delete local feedback</button></div>}<div className="actions"><button className="secondary" onClick={() => setStage("compose")}>Revise modules</button><button className="primary" onClick={() => feedback("helpful")}>Create evaluation draft</button></div></article>}
    </section><footer><span>Consent required · bounded evidence · no code execution</span><button>Reset session</button></footer>
  </main>;
}
createRoot(document.getElementById("root")!).render(<App />);
