export const inventoryIgnoreList = new Set([".git",".gitmodules",".gitignore",".github",".idea",".vscode",".cache",".parcel-cache",".next",".nuxt","node_modules","dist","build","coverage",".nyc_output",".turbo","tmp","temp"]);
export const manifestFileNames = new Set(["package.json","package-lock.json","pnpm-lock.yaml","yarn.lock","bun.lockb","tsconfig.json","vite.config.js","vite.config.ts","webpack.config.js","pyproject.toml","requirements.txt","setup.py","Cargo.toml","go.mod","pom.xml","build.gradle","build.gradle.kts","gradle.properties","composer.json","Gemfile","Makefile","CMakeLists.txt","composer.lock","go.sum","poetry.lock","Gemfile.lock","pubspec.yaml"]);
export const WORKSPACE_MAX_FILES=1000, WORKSPACE_MAX_DEPTH=4, WORKSPACE_MAX_FILE_BYTES=256*1024, WORKSPACE_MAX_METADATA_BYTES=1024*1024;
const privateName=/(^|\/)(\.env(?:\..*)?|.*(?:secret|credential|private.?key|id_rsa).*)$/i, generatedName=/^(dist|build|coverage|generated|\.next|\.turbo)$/i, cacheDirectoryName=/(^|\/)(\.cache|\.tmp|tmp|temp)(\/|$)/i;
export function shouldIgnoreRootEntry(name:string){return inventoryIgnoreList.has(name)}
export function isManifestName(name:string){return manifestFileNames.has(name)}
export function shouldIgnoreAssessmentEntry(relativePath:string,name:string){return !relativePath||relativePath.startsWith("..")||shouldIgnoreRootEntry(name)||privateName.test(relativePath)||generatedName.test(name)||cacheDirectoryName.test(relativePath)}
export function isAllowedAssessmentManifest(name:string){return isManifestName(name)}
export function isGeneratedRootEntry(name:string){return generatedName.test(name)}
export function normalizeGitRemote(remote:string){const t=remote.trim();if(!t)return "";const ssh=t.match(/^[^@:\s]+@([^:]+):(.+)$/);if(ssh)return `${ssh[1]}/${ssh[2]}`.replace(/\.git$/i,"").toLowerCase();try{const u=new URL(t);return `${u.host}${u.pathname}`.replace(/\.git$/i,"").replace(/\/$/,"").toLowerCase()}catch{return t.replace(/\.git$/i,"").toLowerCase()}}
export function parseGitRemoteOutput(output:string){return [...new Set(output.trim().split("\n").map(v=>/^(.+?)\s+(.+?)\s+\((fetch|push)\)$/.exec(v)).filter(Boolean).map(m=>normalizeGitRemote(m![2]!)).filter(Boolean))].sort()}
export interface RepositoryAssessmentManifest{schemaVersion:1;workspaceId:string;repositoryRevision:{headCommit:string|null;branch:string|null;dirty:boolean};topology:{rootEntries:string[];workspaceRoots:string[];manifestFiles:string[]};detected:{languages:Array<{name:string;fileCount:number}>;packageManagers:string[];frameworks:string[];testFrameworks:string[];buildTools:string[];linters:string[];formatters:string[];databaseTechnologies:string[]};commands:{declaredBuild:string[];declaredTest:string[];declaredLint:string[];declaredTypecheck:string[]};architectureSignals:{applicationTypes:string[];packageCount:number;workspaceCount:number};limits:{truncated:boolean;fileCount:number;maxDepth:number;metadataBytes:number}}
